/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SCB_1.h"
#include "SCB_1_SPI_UART.h"
#include "SCB_1_PINS.h"
#include "SCB_1_SPI_UART_PVT.h"
#include "SCB_1_PVT.h"
#include "SCB_1_BOOT.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "TCPWM_1.h"
#include "Clock_1.h"
#include "BLE_1_gatt.h"
#include "BLE_1.h"
#include "BLE_1_HAL_PVT.h"
#include "BLE_1_STACK_PVT.h"
#include "BLE_1_StackGap.h"
#include "BLE_1_StackGatt.h"
#include "BLE_1_StackGattDb.h"
#include "BLE_1_StackHostMain.h"
#include "BLE_1_StackL2cap.h"
#include "BLE_1_StackGattServer.h"
#include "BLE_1_StackGattClient.h"
#include "BLE_1_Stack.h"
#include "BLE_1_eventHandler.h"
#include "BLE_1_custom.h"
#include "ADC_In.h"
#include "ADC_In_aliases.h"
#include "isr_1.h"
#include "SW1.h"
#include "SW1_aliases.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "SW5.h"
#include "SW5_aliases.h"
#include "SW3.h"
#include "SW3_aliases.h"
#include "SW4.h"
#include "SW4_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "I2S_1.h"
#include "I2S_1_PVT.h"
#include "Clock_4.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "SCB_1_SCBCLK.h"
#include "SCB_1_sclk_m.h"
#include "SCB_1_sclk_m_aliases.h"
#include "SCB_1_miso_m.h"
#include "SCB_1_miso_m_aliases.h"
#include "SCB_1_mosi_m.h"
#include "SCB_1_mosi_m_aliases.h"
#include "SCB_1_ss0_m.h"
#include "SCB_1_ss0_m_aliases.h"
#include "BLE_1_bless_isr.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

